### ISSUE TITLE
ValueError: Unknown metric function:top_3_acc while loading model

### ISSUE THREAD

**Issue by vinic15** [jtheiner/SketchRecognition#1]
i tried to load your model using load_model function from keras.models but i am gett this error.
here is my script
import numpy as np
import os
import cv2
from keras.models import load_model
from collections import deque
import sys

model = load_model('model.h5')

def predict_model(model, image):
    image_x = 28
    image_y = 28
    img = cv2.resize(image, (image_x, image_y))
    img = np.array(img, dtype=np.float32)
    processed = np.reshape(img, (-1, image_x, image_y, 1))
    print("processed: " + str(processed.shape))
    pred_probab = model.predict(processed)[0]
    pred_class = list(pred_probab).index(max(pred_probab))
    return max(pred_probab), pred_class

if __name__ == '__main__':
    img=cv2.imread(sys.argv[1])
    print(predict_model(model,img))

**Comment by shubhank008** [comment]
@vinic15 the prediction code only seems to be outputting same value no matter the input ? Tried to input bus and apple doodle drawings from google's quick draw images but the prediction always replies same (which is incorrect too)
```

load complete
processed: (3, 28, 28, 1)
Class: 123
Probab: 1.0
Class: 123
Probab: 1.0
Class: 123
Probab: 1.0

```
