### ISSUE TITLE
How to classify/predict single image in Python ?

### ISSUE THREAD

**Issue by shubhank008** [jtheiner/SketchRecognition#2]
From what I understand, you are grabbing the canvas in android view, turning it into a bitmap and then a array to feed into model.prediction.  
But how can we do this in python code itself if we have a screen/image of the said canvas (aka doodle/drawing).  

I tried using Quick Draw's own images to feed to model but I am missing something as model is expecting 4D input while I tried to pass the image as byte data or numpy array or RGB array, etc.

**Comment by jtheiner** [comment]
The model expects an input of shape (1,28,28,1) or perhaps only (1,28,28). Note, that the first dimension is usually used as batch size and the last for number of channels (in case of an image). I hope I was able to help, though late.
