### ISSUE TITLE
ValueError: Unknow metric function: top_3_acc

### ISSUE THREAD

**Issue by AngelOS95P** [jtheiner/SketchRecognition#3]
When converting from Keras to TensorFlow, it tells me the error: ValueError: Unknow metric function: top_3_acc. I have installed TensorFlow 1.7 from the Sourse.
I have tried with the h5 files used in the project and they give the same error

**Comment by jtheiner** [comment]
I'm able to reproduce the error, but could not find any solution yet.

**Comment by AngelOS95P** [comment]
I have fixed the error by increasing this in the conversion script

def top_3_acc(y_true, y_pred):
    return metrics.top_k_categorical_accuracy(y_true, y_pred, k=3)

And

net_model = load_model('model.h5', custom_objects={'top_3_acc': top_3_acc})
